### ISSUE TITLE
colorfull模板样式不正确

### ISSUE THREAD

**Issue by hainuo** [easysoft/chanzhieps#2]
![snip20151029_1](https://cloud.githubusercontent.com/assets/421861/10817527/6d3a4b14-7e75-11e5-8db7-d4e19b7fe772.png)

跟 演示目录中的图片样式不一样

**Comment by easysoft** [comment]
能说得具体一点吗？




王春生

发件人： hainuo
发送时间： 2015-10-29 19:44
收件人： easysoft/chanzhieps
主题： [chanzhieps] colorfull模板样式不正确 (#2)

跟 演示目录中的图片样式不一样

**Comment by hainuo** [comment]
@easysoft   首先整个界面颜色偏红色，而不是色彩绚烂，这个颜色的话我个人可以接受但是导航栏的字体颜色和各个页面模块的title的颜色均为黑色这个就不能接受了，而且原效果图明确表名是白色， 实际颜色为黑色#333。 通过查看css样式发现为#333 !important 强制色彩为黑色了。请对照效果图来
效果图如下
![](https://raw.githubusercontent.com/easysoft/chanzhieps/master/www/template/default/theme/colorful/preview.png)

**Comment by hainuo** [comment]
颜色校正我做了如下处理
```css
#navbar .nav > li > a{color:#fff !important;}
.panel > .panel-heading{color:#fff;}
#navbar .nav > li> a:hover{color:yellow !important;}
#navbar .nav > li.active >a{color:#ffffff !important;}
```
但是由于不懂less语法，less中对这个处理时使用了全局的一个变量，不知道更改后会引起多大的变化，所以没有对less文件进行修改。关于其他的背景颜色还请官方校对下
